---
layout: post
title: "Splitting a Sample by Multiple Balancing Factors"
author: "Matthew Peverill"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: gfm
    preserve_yaml: true
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
                      encoding = encoding,
                      output_file = file.path(paste0(
                                                  "~/Dropbox/mrpeverill-website/_posts/",
                                                  Sys.Date(),
                                                  '-',
                                                  substr(basename(inputFile), 1, nchar(basename(inputFile)) - 4),
                                                  '.md'
                                                  )
                                              )
                      )
    })
---

```{r setup, include=FALSE,cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(base.dir = "~/Dropbox/mrpeverill-website/", base.url = "/")
knitr::opts_chunk$set(fig.path = "assets/img/BalancedSamplingTest/")
```

This is an example of splitting a sample in two preserving the balance of several variables in R.

```{r,warning=FALSE,results=FALSE,message=FALSE}
library(sn)
library(tidyverse); library(ggthemes); theme_set(theme_tufte())
library(caret)
library(pander)
library(simstudy)
```

# Two factors using caret

```{r}
set.seed(3453)
#rsn samples from a skewed normal distribution
site1<-data.frame(i=rsn(2000,alpha=-3))
site2<-data.frame(i=rsn(4000,alpha=0))
site3<-data.frame(i=rsn(1000,alpha=3))
sitedesc<-factor(c(rep("site.one",2000),
                   rep("site.two",4000),
                   rep("site.three",1000)))
df<-rbind(site1,site2,site3)
df$site<-sitedesc


numbers_of_bins = 10
df <- df %>%
    mutate(
        # bin i:
        i.bin = cut(i,
                    breaks = unique(quantile(
                        i,
                        probs = seq.int(0, 1, by = 1 / numbers_of_bins)
                    )),
                    include.lowest = TRUE,
                    labels=FALSE),
        # interact the factors to make a unique level for each combination.
        interaction = interaction(i.bin, site) 
    )
pander(head(df))
```

Now that the factors are combined, we can sample evenly from them using caret

```{r}
trainIndex<-createDataPartition(df$interaction,p=.5,times=1,list=FALSE)
df$train<-FALSE
df$train[trainIndex]<-TRUE
```

Let's use some plots to verify:

```{r,warning=FALSE,results=FALSE,message=FALSE}
histbysite<-function(plotdata,xvar="i") {
	ggplot(plotdata,aes_string(x=xvar)) +
		geom_histogram() +
		facet_grid(~site)
}
histbysite(df) + ggtitle("Whole Sample")
histbysite(df[df$train,]) + ggtitle("Training")
histbysite(df[!df$train,]) + ggtitle("Test")
```

# Many factors

## Simulate

Let's simulate some other factors to add to our test dataset.

```{r}
simdef<-defData(varname="age",
                dist="categorical",
                formula=genCatFormula(n=5))
simdef<-defData(simdef,varname="sex",
                dist="binary",
                formula=".5")
simdef<-defData(simdef,varname="parent.ed",
                dist="categorical",
                formula=genCatFormula(n=6))
simdef<-defData(simdef,varname="missingdata",
                dist="binary",
                formula=".2")

df2<-cbind(df[,1:3],genData(nrow(df),simdef)) # drop interaction
df2 <- df2 %>%
  select(id, everything()) # put id at the front of the dataset

factorialize<-c("i.bin","age","sex","missingdata","parent.ed")
df2[factorialize] <- lapply(df2[factorialize], factor)

pander(head(df2))
```

Then we partition as above:

```{r}
df2$interaction=interaction(df2[,-c(1:2)])
trainIndex<-createDataPartition(df2$interaction,p=.5,times=1,list=FALSE)
df2$train<-FALSE
df2$train[trainIndex]<-TRUE
```

Testing:

```{r,warning=FALSE,results=FALSE,message=FALSE}

histbysite(df2) + ggtitle("i in Whole Sample")
histbysite(df2[df2$train,]) + ggtitle("i in Training")
histbysite(df2[!df2$train,]) + ggtitle("i in Test")

barbysite<-function(plotdata,xvar="i") {
	ggplot(plotdata,aes_string(x=xvar)) +
		geom_bar() +
		facet_grid(~site)
}

barbysite(df2,"age") + ggtitle("Age in Whole Sample")
barbysite(df2[df2$train,],"age") + ggtitle("Age in Training")
barbysite(df2[!df2$train,],"age") + ggtitle("Age in Test")

barbysite(df2,"missingdata") + ggtitle("missingdata in Whole Sample")
barbysite(df2[df2$train,],"missingdata") + ggtitle("missingdata in Training")
barbysite(df2[!df2$train,],"missingdata") + ggtitle("missingdata in Test")
```
